spring:
  datasource:
    #JDBC配置：
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lwms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&nullCatalogMeansCurrent=true
    username: root
    password: 768928
    
    #连接池配置
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  
  #Failed to start bean ‘documentationPluginsBootstrapper‘ 版本冲突问题
  mvc:
    path match:
      matching-strategy: ant_path_matcher


#MyBatisPlus全局配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  global-config:
    db-config:
      id-type: auto
  
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    call-setters-on-nulls: true


server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /lwms
  port: 8088

# 配置文件添加
knife4j:
  # 是否开启增强配置
  enable: true
  # 是否开启生产环境屏蔽
  production: false
  # 是否开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: root
    # Basic认证密码
    password: 768928
